name: Deploy Python Function

on:
  push:
    branches: [ "main" ]
    paths:
      - "backend-python/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies into package
        run: |
          cd backend-python
          python -m pip install --upgrade pip
          pip install -r requirements.txt --target=".python_packages/lib/site-packages"

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Azure Functions (Python)
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ secrets.AZURE_PY_FUNCTIONAPP_NAME }}
          package: backend-python
